id: P72B6B772
initial_creation_type: ocr
source_metadata:
  volumes:
    c0627b54d3d54e27813079a66606eb83:
      base_file: v066.txt
      image_group_id: I1PD95911
      title: འཕགས་པ་བློ་གྲོས་མི་ཟད་པས་བསྟན་པ་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1470
      volume_number: 66
